name: oci-mysql-db-system-workflow
on:
  push:
    tags:
      - "v*"
jobs:
  build-stack:
    name: Build Stack
    runs-on: ubuntu-latest
    steps:

      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Build Stack'
        run: |
          zip -r stack.zip *

      - name: 'Publish Stack'
        uses: actions/upload-artifact@v2-preview
        with:
          name: 'stack'
          path: 'stack.zip'

      - name: 'Create Release'
        if: success()
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          tag_name: ${{github.ref}}
          release_name: Release ${{github.ref}}
          body: |
            Latest release
          draft: false
          prerelease: false

      - name: 'Upload Release Asset (Stack)'
        if: contains(github.ref, 'v')
        id: upload-release-asset-stack
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          upload_url: ${{steps.create_release.outputs.upload_url}}
          asset_path: ./stack.zip
          asset_name: stack.zip
          asset_content_type: application/zip
